import { randomUUID } from 'node:crypto';
import { query, driver as dbDriver } from '../../../config/database.js';

const TABLE = 'users';
const driver = dbDriver;
const PUBLIC_COLUMNS = 'id, username, email, role, full_name, created_at, updated_at';

function placeholder(index) {
  if (driver === 'mysql') {
    return '?';
  }
  return `$${index}`;
}

export async function findUserByUsername(username) {
  const sql = `SELECT * FROM ${TABLE} WHERE username = ${placeholder(1)}`;
  const res = await query(sql, [username]);
  if (res.rowCount === 0) {
    return null;
  }
  return res.rows[0];
}

export async function findUserById(id) {
  const sql = `SELECT id, username, email, role, full_name, created_at, updated_at FROM ${TABLE} WHERE id = ${placeholder(1)}`;
  const res = await query(sql, [id]);
  if (res.rowCount === 0) {
    return null;
  }
  return res.rows[0];
}

export async function createUser({ username, email, passwordHash, role = 'user', fullName = '' }) {
  if (driver === 'mysql') {
    // MySQL has no INSERT ... RETURNING and the users.id column has no default.
    const id = randomUUID();
    await query(
      `INSERT INTO ${TABLE} (id, username, email, password_hash, role, full_name)
       VALUES (?, ?, ?, ?, ?, ?)`,
      [id, username, email, passwordHash, role, fullName],
    );
    return findUserById(id);
  }

  // PostgreSQL: users.id is generated by the database (gen_random_uuid()).
  const res = await query(
    `INSERT INTO ${TABLE} (username, email, password_hash, role, full_name)
     VALUES ($1, $2, $3, $4, $5)
     RETURNING ${PUBLIC_COLUMNS}`,
    [username, email, passwordHash, role, fullName],
  );
  return res.rows[0];
}

export async function updateUser(id, { username, email, passwordHash, role, fullName }) {
  const sets = [];
  const values = [];
  let idx = 1;

  if (username !== undefined) {
    sets.push(`username = ${placeholder(idx)}`);
    values.push(username);
    idx++;
  }
  if (email !== undefined) {
    sets.push(`email = ${placeholder(idx)}`);
    values.push(email);
    idx++;
  }
  if (passwordHash !== undefined) {
    sets.push(`password_hash = ${placeholder(idx)}`);
    values.push(passwordHash);
    idx++;
  }
  if (role !== undefined) {
    sets.push(`role = ${placeholder(idx)}`);
    values.push(role);
    idx++;
  }
  if (fullName !== undefined) {
    sets.push(`full_name = ${placeholder(idx)}`);
    values.push(fullName);
    idx++;
  }

  if (sets.length === 0) {
    return findUserById(id);
  }

  if (driver === 'mysql') {
    // updated_at is maintained by the column's ON UPDATE CURRENT_TIMESTAMP.
    values.push(id);
    await query(`UPDATE ${TABLE} SET ${sets.join(', ')} WHERE id = ?`, values);
    return findUserById(id);
  }

  sets.push('updated_at = NOW()');
  values.push(id);
  const res = await query(
    `UPDATE ${TABLE} SET ${sets.join(', ')} WHERE id = ${placeholder(idx)} RETURNING ${PUBLIC_COLUMNS}`,
    values,
  );
  return res.rowCount === 0 ? null : res.rows[0];
}

export async function deleteUser(id) {
  const sql = `DELETE FROM ${TABLE} WHERE id = ${placeholder(1)}`;
  const res = await query(sql, [id]);
  // mysql2 reports DELETE results on a ResultSetHeader, not as an array of rows.
  const affected = driver === 'mysql' ? res.rows.affectedRows : res.rowCount;
  return affected > 0;
}

export async function listUsers() {
  const sql = `SELECT id, username, email, role, full_name, created_at, updated_at FROM ${TABLE} ORDER BY created_at ASC`;
  const res = await query(sql);
  return res.rows;
}

export async function findUserByEmail(email) {
  const sql = `SELECT * FROM ${TABLE} WHERE email = ${placeholder(1)}`;
  const res = await query(sql, [email]);
  if (res.rowCount === 0) {
    return null;
  }
  return res.rows[0];
}